== Chapter 6: The Product Owner

It all starts with the Product Owner (PO).

Seriously, the whole idea of Scrum is for a team to work toward the creation of a product that makes stakeholders and customers happy. 

- Who knows what the product's supposed to do?
- Who knows what features the product needs?
- Who has the product vision? 
- Who knows what features matter the most?
- Who can quickly answer questions about the product?
- Who do the stakeholders trust to make decisions about the product?

The answer to all of those questions is 'The Product Owner.'

Who is completely useless in terms of knowing _how_ to build a product, _estimating_ completion times or even _decomposing_ product features into easily manageable chunks? That's probably the Product Owner too. 

The Product Owner (PO) knows the product. Just be careful never to ascribe more competency to the PO than they deserve. Assume they know nothing about actually building a product. That's not what they're accountable for according to Scrum.


=== Product Owners Maximize Value


The Product Owner knows everything there is to know about the product the team's trying to build.

[quote, 2020 Scrum Guide page 5]
____

The Product Owner is accountable for maximizing the value of the product, resulting from the work of the Scrum Team. 

How this is done may vary widely across organizations, Scrum Teams, and individuals.
____

The Product Owner knows all about the Product, but what is the Product Owner most accountable for? The Scrum Guide makes the Product Owner's job clear: to maximize the value of the product being created. 

Interestingly, the Scrum Guide doesn't make it clear how the Product Owner goes about doing that. Fortunately, I can help you out here.

_How do POs Maximize Value?_

The PO maximizes the value of the work done by the Scrum Team by convincing the developers to work on the most important and valuable features of the product first.

- If the PO gets the developers to work on a bunch of features nobody is going to use, the PO _is not_ maximizing value. 

- If the PO gets the developers to create features the clients are dying to get their hands on, the PO _is_ maximizing value. 

That's how the PO maximizes the value of the stuff the developers are delivering. 

=== Product Backlog Management

Effective Product Backlog management is the key to maximizing the work done by the development team. 

[quote, 2020 Scrum Guide page 6]
____
The Product Owner is also accountable for effective Product Backlog management, which includes:

- Developing and explicitly communicating the Product Goal;
- Creating and communicating Product Backlog items;
- Ordering Product Backlog items; and,
- Ensuring that the Product Backlog is transparent, visible, and understood.
____

Take these four bullet points seriously, because Product Backlog Management is one of the 13 categories in which the questions on the Scrum certification exam are categorized. Furthermore, from what I've seen, this category is more heavily weighted on the exam than other categories.

There is a great deal of nuance to the responsibilities, or _accountabilities,_ of the Product Owner. The exam will test your understanding of Product Backlog management by offering false statements or providing incorrect options that seem to make plausible sense.

=== Product Owner Accountabilities

For example, the exam will assert in a True or False question that the _stakeholders_ or _customers_ are responsible for communicating the Product Goal to the team. On the surface, that almost sounds like it makes sense. 

After all, the product is for the customers, right? So shouldn't they communicate the Product Goal? 

Don't fall for the trick. The Product Owner communicates the Product Goal, not the stakeholders or the customers.

The same trick goes for communicating Product Backlog items (PBIs). 

It sounds logical that a customer or stakeholder might be the one creating or communicating details about Product Backlog items, after all, the Product Backlog represent features and functionality that the customers want, right?

Again, don't fall for it. It's the Product Owner's job to create and communicate details about Product Backlog items to the team.

When it comes to the Product Backlog and the Product Goal, the responsibility falls on the shoulders of the Product Owner, nobody else.


==== Test Yourself

****
Who is responsible for managing the Product Backlog and maximizing the value of the product produced? (Choose 1)

* [ ] A) The Scrum Master
* [ ] B) The Product Owner
* [ ] C) The management team
* [ ] D) The development team as a whole
****

Option B is correct.

As we just learned, the Product Owner manages the Product Backlog, and it's also the Product Owner's job to 'maximize the value of the product resulting from the work of the Scrum Team.'

'''

==== Test Yourself

****
Which of the following statements is true? (Choose 1)

* [ ] A) The Scrum Master can add items to both the Sprint Backlog and the Product Backlog
* [ ] B) The Product Owner can add items to both the Sprint Backlog and the Product Backlog
* [ ] C) The Product Owner is fully accountable for all items added to the Product Backlog
* [ ] D) The Scrum Master is fully accountable for all items added to the Sprint Backlog
****

Only Option C is correct.

The developers have full control over the *Sprint* Backlog and only the developers can add to it.

The Product Owner has full control over the *Product* Backlog and only the PO can add items to it.

Notice in the question above the term 'accountable' was used.

The Product Owner can delegate any of the work they are accountable for to anyone they deem fit. However, the Product Owner remains fully accountable for the results, regardless of who does the work.

'''

==== Test Yourself

****
True or False: It is the job of the Scrum Master to ensure that items in the Product Backlog are properly understood by both stakeholders and team members.
****

This is false. It is stated quite clearly in the Scrum Guide that it is the job of the _Product Owner_ to make sure "that the Product Backlog is transparent, visible and _understood._"

Nobody should be expected to 'get into the head' of the Product Owner and assume what they are thinking. 

While the Product Owner's vision may not always be complete, what vision they do have should be clear to everyone involved in the project.

=== Who Does the Product Owner's Work?

In Scrum, the developers do the development.

In Scrum, the Scrum Master does the Scrum Mastering.

Yet according to the Scrum Guide, the Product Owner can get someone else to do the gruntwork for them, just so long as they remain responsible and accountable for the final results.

[quote, 2020 Scrum Guide page 6]

____
The Product Owner may do the Product Backlog management work, or they may delegate the responsibility to others. 

Regardless, the Product Owner remains accountable.
____

=== Product Ownership and Trust


Perhaps the most important quality of the Product Owner is that they have the complete and total trust of the organization to make decisions about what's best for the product being built.

[quote, 2020 Scrum Guide page 6]
____
For Product Owners to succeed, the entire organization must respect their decisions. 
____

The importance of PO trust can't be understated with regards to product development.

- Scrum teams move quickly
- Conditions change from day to day
- Adaptation should happen constantly
- Product Backlog item clarity is of utmost importance


When developers have questions about the work they're doing, they need answers that are clear and definitive. The Product Owner must be able to respond quickly, and the development team needs to know that the decisions of the Product Owner will not be second-guessed by management. 

If someone else in the organization keeps overriding the decisions of the PO, the team will quickly lose trust in the Product Owner, and the whole Scrum framework falls apart.

NOTE: Notice how the Scrum pillars of transparency, inspection and adaptation always arise when talking about Scrum events, accountabilities and artifacts. 

<<<




=== A Single Product Owner

The job of the Product Owner cannot be shared amongst multiple individuals. There can't be two co-Product Owners on a team.

As the Scrum Guide stated earlier, the Product Owner can delegate some of the Product Backlog management work to a cohort, but in the end, all of the accountabilities associated with being a Product Owner fall on the shoulders of only one person: the PO.

[quote, 2020 Scrum Guide page 6]
____
The Product Owner is one person, not a committee. 

The Product Owner may represent the needs of many stakeholders in the Product Backlog.
____

Notice how the Scrum Guide states that the Product Owner may represent the needs of many stakeholders. Implied in that statement is that different stakeholders might have different interests about which features or enhancements should be prioritized.

When it comes to competing interests, the Product Owner is responsible for managing expectations and building a consensus amongst the stakeholders.





=== Keeping Tabs on the Product Owner

Stakeholders will always be interested in how the product is progressing. They will constantly want to know what's been created and what the team will be working on next. 

The three Scrum artifacts, namely the Product Backlog, Sprint Backlog, and inspectable Increments are how stakeholders get the answers to their questions about how the project is progressing.

[quote, 2020 Scrum Guide page 6]
____
The entire organization must respect the PO's decisions. These decisions are visible in two ways:

1. through the content and ordering of the Product Backlog
2. through the inspectable Increment at the Sprint Review

Those wanting to change the Product Backlog can do so by trying to convince the Product Owner.
____



==== Test Yourself

****
Important decisions that about the future direction of the product being built must be made by: (Choose 1)

* [ ] A) The Scrum Master
* [ ] B) The Product Owner
* [ ] C) The Product Owner along with a stakeholder committee
* [ ] D) Stakeholders or executive management
****

The answer to this question is B, the Product Owner.

The Scrum Guide states quite emphatically that product-based decisions are not to be made by a committee. 

'''

==== Test Yourself

****
There are many stakeholder groups with many competing interests, including the priority of features, the cost of the project, the release date, and community outreach. 

How does Scrum ensure the interests of each of these groups are recognized and respected? (Choose 1)

* [ ] A) Have the Scrum Master represent the interests of each stakeholder group
* [ ] B) Have multiple Scrum Masters, with a different Scrum Master assigned to each stakeholder group
* [ ] C) Have one Product Owner represent the interests of each stakeholder group
* [ ] D) Have multiple Product Owners, with a different Product Owner assigned to each stakeholder group
****

The answer is C.

There is only one Product Owner on a Scrum Team, and that one Product Owner represents the interests of all the stakeholders.

'''

=== Trust, Transparency, and the Product Backlog

The PO must have the complete and total trust of the organization concerning product ownership, but trust is a two-way street. 

If the Product Owner is to be trusted, the Product Owner must also be transparent about what they are doing.

So how does the Product Owner make their decisions transparent? They do so by making the Product Backlog visible and available to all stakeholders.

- Want to know what the Product Owner is building? Look at the Product Backlog.
- Want to know what the Product Owner has prioritized? Look at the Product Backlog.
- Want to know what the Product Owner wants to build next? Look at the Product Backlog.
- Want to know how features are described? Look at the Product Backlog.
- Want to know the vision and goal for the product? Look at the Product Backlog's Product Goal.

The Prodcut Backlog is the key to making the decisions of the Product Owner transparent.

<<<

=== Inspection of the Increment



If a stakeholder wants to know what needs to be done, they look at the Product Backlog. 

If a stakeholder wants to know what's being done, they look at the Product Backlog items that are part of the current Sprint's backlog.

At the end of every Sprint, a Sprint Review takes place where stakeholders inspect the Product Backlog items that have met the Definition of Done to produce a product Increment.

The Product Owner's commitment to visibility and transparency with regard to the Product Backlog is what builds confidence and allows management to have trust in the Scrum framework.

=== Negotiating Product Features

Not everyone will agree with what should be built next, what features should be prioritized, or how product development should be managed.

- Stakeholders might disagree. 
- The Scrum Master might disagree. 
- The Developers might disagree. 

Disagreement is expected, especially in a fast-moving environment where things change quickly.

If anyone wants to change the Product Backlog, update the Product Backlog, delete something from the Product Backlog, or add something to the Product Backlog, they go through the Product Owner.

When it comes to the Product, and the Product Backlog that describes everything that needs to be built, the Product Owner has full control.

==== Test Yourself

****
How does the Product Owner ensure their decisions are transparent and open?
(Choose 3) 

* [ ] A) By making their decisions visible in the Product Backlog
* [ ] B) By allowing stakeholders to see how the Product Backlog has been ordered and prioritized
* [ ] C) By sending regular status updates to stakeholders.
* [ ] D) By scheduling weekly meetings between the Scrum Developers and stakeholders

****

Options A and B are correct.

Everyone who has 'skin in the game' is allowed access to the Product Backlog. This allows stakeholders, developers and every team member to know exactly what needs to be built.

The ordering of the Product Backlog also allows stakeholders to know which items have been given top priority, and which items are less likely to be developed in the near future.



==== Test Yourself

****

The CEO has told you, the Scrum Master, that if a key feature isn't added to the product within the next three week, the project will be cancelled. 

What action should you, the Scrum Master, take? (Choose 1)

* [ ] A) Add the feature as a Sprint Backlog item so developers can start working on it immediately
* [ ] B) Add a new item to the Product Backlog to represent the feature
* [ ] C) Cancel the Sprint and have the developers shift their focus to this new feature
* [ ] D) Inform the Product Owner and facilitate a conversation between the Product Owner and the CEO

****

Option D is correct.

If a change needs to be made to the Product Backlog, it's the Product Owner who does it. 

If the CEO needs a feature prioritized, the CEO has to go through the Product Owner. 

Nobody has the right to add features to the Product Backlog other than the Product Owner, and nobody can inform the developers about which items are the highest priority other than the Product Owner.

'''
