
== About the Practice Exams

The second part of this book is all about testing you on your knowledge of the Scrum Guide, and possibly introducing you to some of the unexpected ways the test makers use to evaluate your knowledge.

- The last exam is 40 questions, and I believe it is slightly harder than the actual exam.
- The two exams prior to that are 25 questions long and are a good approximation to the Scrum Master certification exam's difficulty
- The two exams that kick off the start of this section? Well, they're unusual.

Let me explain.

=== The Secret Test-Taking Trick

There's a trick to answering the toughest questions on the Scrum Master exam, but I'd like you to take the first practice exam first before the trick is revealed.

The questions in the first practice exam fall on the harder side of what to expect on the Scrum Master certification exam, so don't get discouraged if they seem difficult. That's intentional.

When you complete the first practice exam, I'll reveal the trick to you and test you on a set of questions similar to those in the first exam, but with the trick applied. 

I think you'll find it makes a big difference.

Now get started with the practice exams. Good luck!

== Exam 1

=== Questions

==== Question 1

True or false: Scrum is a proven and complete software development process.


==== Question 2


Which of the following statements are true about the Scrum Master role?

* [ ] A.	The Scrum Master cannot be one of the developers on the team
* [ ] B.	The Scrum Master cannot also be the team's Product Owner
* [ ] C.	The Scrum Master cannot be one of the product's stakeholder
* [ ] D.	The Scrum Master can be a stakeholder and a developer at the same time


==== Question 3

The Scrum Team has just been assembled, but the IT department has been slow to provision resources like laptops, software, build tools and test environments.

The team does not want to start the first Sprint next week given the lack of preparedness.

How would you as the Scrum Master recommend the team proceed?

* [ ] A.	Explain to the organization that 'Sprint 0' exists to allow the team to get prepared for development
* [ ] B.	Ask the team to work toward the development of a small, valuable increment despite the lack of preparedness
* [ ] C.	Declare this an infrastructure Sprint where developers simply configure their tools and software
* [ ] D.	Delay the start of the Sprint until the organization can properly provision the required tools and infrastructure



==== Question 4 

A developer has completed a feature that when integrated into the codebase will create a valuable and usable increment. Completion of the Sprint Goal depends upon it.

When should the developer integrate their work into the product?

* [ ] A.	During the Daily Scrum, after achieving consensus with the other developers
* [ ] B.	After the development Sprint finishes with the consent of the Scrum Master
* [ ] C.	Immediately so long as the work meets the team's definition of done
* [ ] D.	During the Sprint Review so stakeholders can witness the integration



==== Question 5


A developer has identified a troublesome and worrying security vulnerability in the codebase and has asked you, the Scrum Master, what should be done about it. 

What guidance should you provide the developer on this topic?

* [ ] A.	Have the developer make this issue as a top priority item in tomorrow's Daily Scrum
* [ ] B.	Have the developer discuss the issue with the Product Owner and plan to fix the issue in the next Sprint
* [ ] C.	Have the developer discuss the issue with developers right away
* [ ] D.	Have the developer raise the issue as a priority item during the next Sprint Planning meeting


==== Question 6

 Under which circumstance are developers allowed to discuss product development directly with stakeholders?

* [ ] A.	Developers can speak directly with stakeholders during the Sprint Retrospective
* [ ] B.	Developers can speak directly with stakeholders so long as the Product Owner is present
* [ ] C.	Developers can speak directly with stakeholders with permission from the Scrum Master
* [ ] D.	Developers are not allowed speak directly with stakeholders
* [ ] E.	Developers can speak directly with stakeholders at any time


==== Question 7

Human Resources has just hired the three new programmers that were required in order to keep development progressing at a sustainable pace. However, these programmers have arrived right in the middle of a four week Sprint.

As the Scrum Master, when do you advise these programmers be added to the development effort?

* [ ] A.	At the moment they arrive 
* [ ] B.	At the end of the current Sprint but before the next Sprint begins
* [ ] C.	At the following day's Daily Scrum
* [ ] D.	During the next Sprint Planning event



==== Question 8

Given a well-functioning team of 4 developers, what impact will the addition of 3 new developers likely have on the productivity of the existing team members?

* [ ] A.	Individual productivity will increase permanently
* [ ] B.	Individual productivity will increase over the short term
* [ ] C.	Individual productivity will decrease permanently
* [ ] D.	Individual productivity will decrease over the short term



==== Question 9

Developers have become frustrated with the fact that peripheral tasks like quality control, user acceptance testing and documentation have taken away from their core development efforts, subsequently putting the project at risk.

How would you advise the team to move forward?
* [ ] A.	Have the Scrum team create a sub* [ ] A.team dedicates to QA, UAT testing and documentation
* [ ] B.	Have the Scrum team outsource QA, UAT and documentation to a third party
* [ ] C.	Have the Product Owner remove quality control, testing and documentation from the definition of done
* [ ] D.	Advise the Scrum Team they are responsible for all aspects of delivering a product increment



==== Question 10

Unforeseen circumstances have reduced developer productivity and half* [ ] A.way through the Sprint it is clear that the Sprint Plan must change drastically in order for the Sprint Goal to be achieved.

What guidance would you, as the Scrum Master, provide to the team?

* [ ] A.	Tell the developers to cancel the development Sprint and start a new Sprint Planning session
* [*] B.	Have the developers regroup and update the Sprint Plan as soon as possible
* [ ] C.	Have the developers dedicate time during the next Daily Scrum to update the Sprint Goal
* [ ] D.	Tell the developers the Sprint Plan cannot change and have them continue working as planned towards the Sprint Goal


=== Answers


==== Question 1

True or false: Scrum is a proven and complete software development process.

This is false for three reasons:

1. Scrum is not a process or a methodology. Scrum is a lightweight framework.
2. Scrum can be used to develop any product, not just a software product.
3. Scrum self-describes as an incomplete framework. 

"Scrum is a lightweight framework that helps people, teams and organizations generate value through adaptive solutions for complex problems. The Scrum framework is purposefully incomplete."  - The Scrum Guide, page 3.

==== Question 2


Which of the following statements are true about the Scrum Master role?

* [ ] A.	The Scrum Master cannot be one of the developers on the team
* [ ] B.	The Scrum Master cannot also be the team's Product Owner
* [ ] C.	The Scrum Master cannot be one of the product's stakeholder
* [*] D.	The Scrum Master can be a stakeholder and a developer at the same time

Option D is correct.

There are no rules in the Scrum Guide that say a person cannot take on multiple roles or accountabilities at the same time. 

In fact, on small startups, it's not uncommon for the Scrum Master to also be a stakeholder while also helping out with development. Furthermore, if the Product Owner got sick, that person might even take on Product Owner accountabilities temporarily as well.

The only rule the Scrum Guide provides on a Scrum Master or Product Owner doing development is that when they do help to build the product, they must participate in the Daily Scrum as a developer.

"If the Product Owner or Scrum Master are actively working on items in the Sprint Backlog, they participate [in the Daily Scrum] as Developers." -The Scrum Guide, page 9.

==== Question 3

The Scrum Team has just been assembled, but the IT department has been slow to provision resources like laptops, software, build tools and test environments.

The team does not want to start the first Sprint next week given the lack of preparedness.

How would you as the Scrum Master recommend the team proceed?

* [ ] A.	Explain to the organization that 'Sprint 0' exists to allow the team to get prepared for development
* [*] B.	Ask the team to work toward the development of a small, valuable increment despite the lack of preparedness
* [ ] C.	Declare this an infrastructure Sprint where developers simply configure their tools and software
* [ ] D.	Delay the start of the Sprint until the organization can properly provision the required tools and infrastructure

Option B is correct.

There is no such thing as an infrastructure Sprint or a Sprint 0 in Scrum.

Every Sprint must attempt to develop and increment of value that will be part of the final product.

No organization is ever sufficiently prepared for development to begin. If Scrum teams waited for all of the tools they require to be provisioned and available before they started to work, it's unlikely that any work would ever get done.



==== Question 4 

A developer has completed a feature that when integrated into the codebase will create a valuable and usable increment. Completion of the Sprint Goal depends upon it.

When should the developer integrate their work into the product?

* [ ] A.	During the Daily Scrum, after achieving consensus with the other developers
* [ ] B.	After the development Sprint finishes with the consent of the Scrum Master
* [*] C.	Immediately so long as the work meets the team's definition of done
* [ ] D.	During the Sprint Review so stakeholders can witness the integration

Option C is correct.

If a developer completes any work that meets the definition of done, it should be immediately integrated into the product.

If work cannot be integrated into the product being built, it is not useful and it does not create a valid increment. Integration, and ensuring that work does indeed integrate, is essential.

A developer doesn't need anyone's permission to integrate their work into the product.

If there is a piece of work that is complete and can be successfully integrated into the final product, it should be integrated immediately. Waiting serves no purpose, nor is it in line with Scrum's adherence to lean thinking.

==== Question 5


A developer has identified a troublesome and worrying security vulnerability in the codebase and has asked you, the Scrum Master, what should be done about it. 

What guidance should you provide the developer on this topic?

* [ ] A.	Have the developer make this issue as a top priority item in tomorrow's Daily Scrum
* [ ] B.	Have the developer discuss the issue with the Product Owner and plan to fix the issue in the next Sprint
* [*] C.	Have the developer discuss the issue with developers right away
* [ ] D.	Have the developer raise the issue as a priority item during the next Sprint Planning meeting

Option C is correct.

If there is a serious security flaw in the codebase, it's an issue that should be raised immediately with the development team.

Scrum provides a number of events, such as the Daily Scrum and the Sprint Retrospective, to encourage discussion. However, the existence of these events should never stand in the way of pragmatic or essential discussions between members of the team.

If an emergency arises, it should be addressed immediately. Don't wait for a scheduled Scrum event to adapt to changing conditions.

==== Question 6

 Under which circumstance are developers allowed to discuss product development directly with stakeholders?

* [ ] A.	Developers can speak directly with stakeholders during the Sprint Retrospective
* [ ] B.	Developers can speak directly with stakeholders so long as the Product Owner is present
* [ ] C.	Developers can speak directly with stakeholders with permission from the Scrum Master
* [ ] D.	Developers are not allowed speak directly with stakeholders
* [*] E.	Developers can speak directly with stakeholders at any time

Option E is correct.

There are no rules in Scrum that restricts a developer talking to a stakeholder.

One of the Scrum pillars is transparency. One of the Scrum values is openness. What does it say about transparency and openness of an organization put rules and restrictions around when a developer might be allowed to talk to a stakeholder?

The Product Owner is responsible for speaking with stakeholders and discovering which features and functionality they value most. 

However, in terms of speaking with developers about the Sprint Backlog, Product Backlog, Sprint Goal or anything else, there is nothing in the Scrum Guide that restricts such discussions. In fact, Scrum encourages it.

==== Question 7

Human Resources has just hired the three new programmers that were required in order to keep development progressing at a sustainable pace. However, these programmers have arrived right in the middle of a four week Sprint.

As the Scrum Master, when do you advise these programmers be added to the development effort?

* [*] A.	At the moment they arrive 
* [ ] B.	At the end of the current Sprint but before the next Sprint begins
* [ ] C.	At the following day's Daily Scrum
* [ ] D.	During the next Sprint Planning event

Option A is correct.

If your project needs programmers to assist in the development effort, why would you wait even one minute to add them to the team and get them contributing to the development effort?

Note that there is no delay in Scrum between the time when one Sprint ends and the next Sprint begins. When one Sprint ends, the next Sprint starts immediately.

==== Question 8

Given a well-functioning team of 4 developers, what impact will the addition of 3 new developers likely have on the productivity of the existing team members?

* [ ] A.	Individual productivity will increase permanently
* [ ] B.	Individual productivity will increase over the short term
* [ ] C.	Individual productivity will decrease permanently
* [*] D.	Individual productivity will decrease over the short term

Option D is correct.

The onboarding process of new team members often pulls existing developers away from their normal routines, as they spend time with new devs explaining the product, helping them connect to GitHub, set up a printer and even find the restroom.

Over the long run, individual productivity should go back to normal, but in the short term it will decrease.

==== Question 9

Developers have become frustrated with the fact that peripheral tasks like quality control, user acceptance testing and documentation have taken away from their core development efforts, subsequently putting the project at risk.

How would you advise the team to move forward?
* [ ] A.	Have the Scrum team create a sub-team dedicates to QA, UAT testing and documentation
* [ ] B.	Have the Scrum team outsource QA, UAT and documentation to a third party
* [ ] C.	Have the Product Owner remove quality control, testing and documentation from the definition of done
* [*] D.	Advise the Scrum Team they are responsible for all aspects of delivering a product increment

Option D is correct.

There are no sub-teams in Scrum, nor are their any hierarchies of developers.

"Within a Scrum Team, there are no sub-teams or hierarchies. It is a cohesive unit of professionals." - The Scrum Guide, page 5.

If there is a backlog item that requires documentation to be generated, or the definition of done requires a set of user acceptance tests (UAT) to e performed, then it is the job of the individuals of the development team to get those tasks done.

The developers of the Scrum Team are responsible for the end-to-end development of all features in the Product Backlog with full compliance to any non-functional requirements the definition of done may demand.

==== Question 10

****

Unforeseen circumstances have reduced developer productivity and half-way through the Sprint it is clear that the Sprint Plan must change drastically in order for the Sprint Goal to be achieved.

What guidance would you, as the Scrum Master, provide to the team?

* [ ] A.	Tell the developers to cancel the development Sprint and start a new Sprint Planning session
* [*] B.	Have the developers regroup and update the Sprint Plan as soon as possible
* [ ] C.	Have the developers dedicate time during the next Daily Scrum to update the Sprint Goal
* [ ] D.	Tell the developers the Sprint Plan cannot change and have them continue working as planned towards the Sprint Goal

****

Option B is correct.

If circumstances change and the developers need to update their plan, they should update their plan immediately. 

During the Sprint, the Sprint Goal cannot change, nor can a Sprint be cancelled on the whim of the Scrum Master or the developers.

What can change is the Sprint Plan, and it's expected to be updated throughout the sprint as conditions change and more is learned about the product being developed.

Developers should certainly not wait for a scheduled event like the Daily Scrum to adapt their plan if it's necessary.

"The Daily Scrum is not the only time Developers are allowed to adjust their plan. They often meet throughout the day for more detailed discussions about adapting or re* [ ] A.planning." –The Scrum Guide, page 9.
