---
layout: default 
title: "814 - Which two of the following are true abou"
---


[#question]
== 814-63effa469ebbe935e4c16a93.

****

[#query]
--
Which of the following would be responsibilities a team's Scrum Master would fulfill?
--

[#list]
--
* [ ] A. At the Sprint Review, the Scrum Master identifies which backlog items have met the Definition of Done and which have not.
* [*] B. The Scrum Master coaches the Scrum Team on the importance of keeping Scrum events within their timebox.
* [*] C. The Scrum Master helps to advise on and plan Scrum implementations within their organization.
* [ ] D. The Scrum Master will assign tasks to development team members in order to maximize their utilization.
* [ ] E. The Scrum Master is responsible for updating Agile tools such as JIRA and generating Sprint burn-down charts for the team.

--
****

[#answer]
BC

[#explanation]
--
The Scrum Master is responsible for ensuring the Scrum framework is followed by the team and that the team is continuously improving. Two key aspects of this responsibility are facilitating timeboxed meetings and coaching people on Scrum values.

The Scrum Master is also responsible for helping their organization to plan for Scrum adoption and advise on how to implement Scrum successfully.

From the Scrum Guide:

The Scrum Master serves the organization in several ways, including:

- Leading, training, and coaching the organization in its Scrum adoption;
- Planning and advising Scrum implementations within the organization;
- Helping employees and stakeholders understand and enact an empirical approach for complex work; and,
- Removing barriers between stakeholders and Scrum Teams.

--

[#ka]
Coaching and Mentoring

'''

