---
layout: default 
title: "822 - A member of the Development Team takes t"
---


[#question]
== 822-63effb9d9ebbe935e4c16abd.

****

[#query]
--
A developer has come to you, the Scrum Master, expressing concerns about the lax attitudes the team has towards data privacy and security. The concerned developer believes there are serious security vulnerabilities in the existing code.

How should the Scrum Master first respond to a Scrum Developer expressing such concerns?
--

[#list]
--
* [ ] A. Ask the Product Owner to add security to the definition of done.
* [ ] B. Ask the development team to stop further development of features until the issues are addressed.
* [ ] C. Ask the Product Owner to add a Product Backlog item for security and push it to the top of the Product Backlog.
* [ ] D. Check with the organization's security team to see if the concerns are valid.
* [*] E. Have the developer share their concerns with the team and have the team decide on a course of action.

--
****

[#answer]
E

[#explanation]
--

A Scrum Developer should discuss security concerns immediately with their development team rather than waiting for a Sprint Review or Sprint Retrospective to do so.

If the developer does not feel comfortable discussing the issue with the team, that points to an even deeper problem with team dynamics, which is an impediment to transparency. This would be an impediment the Scrum Master would be interested in coaching around.


--

[#ka]
Coaching and Mentoring

'''

