---
layout: default 
title: "868 - Which of the following might the Scrum T"
---


[#question]
== 868-63effcd19ebbe935e4c16af0.

****

[#query]
--

Teams sometimes struggle to come up with items to discuss during the Sprint Retrospective.

Which of the following topics and issues would be worthwhile for a Scrum Team to discuss during a Sprint Retrospective?

--

[#list]
--
* [ ] A. Whether the Definition of Done needs to be updated.
* [ ] B. Whether the length of the Sprint needs adjusting.
* [ ] C. How to better decompose Product Backlog items during Sprint Planning.
* [ ] D. How to improve communication between on-site and remote workers.
* [*] E. All of the above.

--
****

[#answer]
E

[#explanation]
--
All of these topics are commonly discussed in the Sprint Retrospective.

From the Scrum Guide: "[During the Sprint Retrospective,] the Scrum Team inspects how the last Sprint went with regards to:

- Individuals
- Interactions
- Processes
- Tools,
- The Definition of Done. 

Inspected elements often vary with the domain of work."

Remember that only members of the Scrum Team are invited to the Sprint Retrospective. This is in stark contrast to the Sprint Review where anyone with a stake in the development of the product can attend.


--

[#ka]
Events

'''

