---
layout: default 
title: "852 - Which three of the following are timebox"
id: 852-63effa599ebbe935e4c16a95.
---


[#question]
== 852-63effa599ebbe935e4c16a95.

****

[#query]
--
Which of the following Scrum events are timeboxed to limit the amount of time spent on them?
--

[#list]
--
* [ ] A. Standup Meetings.
* [ ] B. The Release Sprint.
* [*] C. The Sprint Retrospective.
* [*] D. Sprint Planning. 
* [ ] E. Stakeholder Meetings.
* [ ] F. Sprint Zero.
* [*] G. The Daily Scrum.

--
****

[#answer]
CDG

[#explanation]
--
The Sprint Retrospective is a timeboxed event that occurs at the end of each Sprint and allows the team to reflect on their processes and identify areas for improvement. The Sprint Retrospective is timeboxed to a maximum of 3 hours.

Sprint Planning is also timeboxed and occurs at the beginning of each Sprint, allowing the team to plan and prioritize their work for the upcoming Sprint. Sprint Planning is timeboxed to a maximum of 8 hours.

The Daily Scrum is another timeboxed event that occurs daily during the Sprint and allows the team to synchronize their work and plan for the day. The Daily Scrum is timeboxed to a maximum of 15 minutes.

The Sprint Review is also timeboxed to a maximum of 4 hours, although the Sprint Review was not mentioned in this question.

Options A, B, E, and F are not correct because they are not Scrum events. On any Scrum exam, references to standup meetings, release Sprints, stakeholder meetings and Sprint Zero will likely be red herrings designed to trick you into selecting an incorrect answer. These topics are never mentioned at all in the Scrum Guide.


--

[#ka]
Events

'''
