---
layout: default 
title: "913 - The Product Owner must release each Incr"
---


[#question]
== 913-63efff349ebbe935e4c16b38.

****

[#query]
--
During every Sprint, the team attempts to create at least one Increment to present to stakeholders during the Sprint Review.

Why might a Product Owner refuse to immediately release an Increment into production after a successful Sprint Review?
--

[#list]
--
* [ ] A. Increments are automatically released into production so it is not possible to refuse a release.
* [ ] B. The Product Owner needs confirmation from the Scrum Master in order to release an Increment into production.
* [*] C. The immediate timing of the release does not make sense for customers or stakeholders.
* [ ] D. The Product Owner never refuses to release an Increment into production.

--
****

[#answer]
C

[#explanation]
--
If the timing of the release of an Increment is not in the best interest of users or stakeholders, the Product Owner does not need to release it immediately.

For example, a Christmas Theme for the website might be completed in late October. You wouldn't publish the website's Christmas theme two months before Christmas.

Increments don't need to be released or published immediately. They can be released when they make the most sense for the organization, stakeholders and customers.

--

[#ka]
Forecasting and Release Planning

'''

